apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/naousse/cloudk8s:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/naousse/cloudk8s:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: cloudk8s
        chartPath: charts/cloudk8s
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/naousse/cloudk8s"
          image.tag: "{{.TAG}}"
